<?php


    $etablissements_places= [ 
        "Annecy" => 0,
        "Auxerre" => 25 ,
        "Bethune" => 20 ,
        "Beziers" => 20 ,
        "Blagnac" => 25 ,
        "Blois" => 0 ,
        "Caen-Ifs" => 20 ,
        "Chalons-en-Champagne" => 20 ,
        "Clermont-Ferrand" => 20 ,
        "Colmar" => 0 ,
        "Grenoble" => 0 ,
        "Kourou" => 0 ,
        "La Reunion" => 20 ,
        "La Roche sur Yon" => 0 ,
        "La Rochelle" => 20 ,
        "Lannion" => 20 ,
        "Luminy" => 0 ,
        "Mont de Marsan" => 18 ,
        "Montbeliard" => 0 ,
        "Nancy" => 20 ,
        "Poitiers" => 0 ,
        "Roanne" => 0 ,
        "Rouen-Elbeuf" => 0 ,
        "Saint-Malo" => 0 ,
        "Sophia" => 0 ,
        "Valence" => 0 ,
        "Velizy" => 0 ,
        "Villetaneuse" => 20 ,
        "Vitry" => 0 ,
    ];


    $etablissements= array (
        "",
        "Annecy",
        "Auxerre",
        "Bethune",
        "Beziers",
        "Blagnac",
        "Blois",
        "Caen-Ifs",
        "Chalons-en-Champagne",
        "Clermont-Ferrand",
        "Colmar",
        "Grenoble",
        "Kourou",
        "La Reunion",
        "La Roche sur Yon",
        "La Rochelle",
        "Lannion",
        "Luminy",
        "Mont de Marsan",
        "Montbeliard",
        "Nancy",
        "Poitiers",
        "Roanne",
        "Rouen-Elbeuf",
        "Saint-Malo",
        "Sophia",
        "Valence",
        "Velizy",
        "Villetaneuse",
        "Vitry",
    );

    $etablissements_full= array (
        "",
        "01 - Annecy",
        "02 - Auxerre",
        "03 - Bethune",
        "04 - Beziers",
        "05 - Blagnac",
        "06 - Blois",
        "07 - Caen-Ifs",
        "08 - Chalons-en-Champagne",
        "09 - Clermont-Ferrand",
        "10 - Colmar",
        "11 - Grenoble",
        "12 - Kourou",
        "13 - La Reunion",
        "14 - La Roche sur Yon",
        "15 - La Rochelle",
        "16 - Lannion",
        "17 - Luminy",
        "18 - Mont de Marsan",
        "19 - Montbeliard",
        "20 - Nancy",
        "21 - Poitiers",
        "22 - Roanne",
        "23 - Rouen-Elbeuf",
        "24 - Saint-Malo",
        "25 - Sophia",
        "26 - Valence",
        "27 - Velizy",
        "28 - Villetaneuse",
        "29 - Vitry",
    );
?>
